# Generated by Django 6.1.1 on 2026-10-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Regra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=10, unique=True)),
                ("assunto", models.CharField(max_length=100)),
                ("pergunta", models.CharField(max_length=200)),
                ("trecho", models.CharField(max_length=50)),
                ("palavras_chave", models.CharField(max_length=200)),
                ("resposta", models.TextField()),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
    ]
